# Generated by Django 6.0.3 on 2026-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("technical_score", models.IntegerField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
