# Generated by Django 5.2.12 on 2026-03-06 15:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_final_ats_score_resume_initial_ats_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
    ]
