# Generated by Django 6.0.3 on 2026-03-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interviews", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview",
                to="jobs.application",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="interviews.interview",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="interviews.interview",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="interviews.question",
            ),
        ),
    ]
