# Generated by Django 5.2.12 on 2026-03-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AptitudeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LOGICAL", "Logical Reasoning"),
                            ("QUANTITATIVE", "Quantitative Aptitude"),
                            ("DATA", "Data Interpretation"),
                        ],
                        default="LOGICAL",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=512)),
                ("option_b", models.CharField(max_length=512)),
                ("option_c", models.CharField(max_length=512)),
                ("option_d", models.CharField(max_length=512)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="conversation_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="AptitudeTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="LOGICAL", max_length=20)),
                ("score", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aptitude_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(blank=True, default="General", max_length=255),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_score", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("conversation_history", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer", models.TextField()),
                ("score", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="interviews.practiceinterview",
                    ),
                ),
            ],
        ),
    ]
