# Generated by Django 5.2.12 on 2026-03-05 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_aptitudequestion_interview_conversation_history_and_more"),
        ("jobs", "0004_job_domain_job_experience_job_location_job_salary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[("AI", "AI Interview"), ("LIVE", "Live Interview")],
                        default="AI",
                        max_length=20,
                    ),
                ),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical Round"),
                            ("AI_SCREENING", "AI Screening"),
                            ("FINAL", "Final Round"),
                        ],
                        default="AI_SCREENING",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                            ("Missed", "Missed"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("final_score", models.IntegerField(blank=True, null=True)),
                ("strengths", models.TextField(blank=True, null=True)),
                ("weaknesses", models.TextField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="jobs.application",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("score", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_records",
                        to="interviews.interviewschedule",
                    ),
                ),
            ],
        ),
    ]
