# Generated by Django 5.2.12 on 2026-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_interviewschedule_interviewattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                    ("Missed", "Missed"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
