# Generated by Django 5.2.12 on 2026-03-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_interviewschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudetestresult',
            name='detailed_responses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aptitudetestresult',
            name='domain_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='category',
            field=models.CharField(choices=[('APTITUDE', 'Aptitude'), ('LOGICAL', 'Logical Reasoning'), ('COMMUNICATION', 'Communication Skills'), ('DOMAIN', 'Domain-Based')], default='LOGICAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='aptitudetestresult',
            name='category',
            field=models.CharField(default='FULL_TEST', max_length=20),
        ),
    ]
