# Generated by Django 5.2.12 on 2026-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0006_aptitudetestresult_detailed_responses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptitudetestresult",
            name="fullscreen_violations",
            field=models.IntegerField(default=0),
        ),
    ]
