# Generated by Django 5.2.12 on 2026-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0007_aptitudetestresult_fullscreen_violations"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptitudetestresult",
            name="tab_violations",
            field=models.IntegerField(default=0),
        ),
    ]
