# Generated by Django 5.2.12 on 2026-03-13 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0008_aptitudetestresult_tab_violations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aptitudetestresult",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProctoringViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_id",
                    models.CharField(
                        help_text="Identifier for the test (e.g., 'aptitude_1' or 'interview_5')",
                        max_length=100,
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("phone_detected", "Phone Detected"),
                            ("multiple_persons", "Multiple Persons Detected"),
                            ("no_face_detected", "No Face Detected"),
                            ("tab_switch", "Tab Switch"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
