# Generated by Django 5.2.12 on 2026-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0009_alter_aptitudetestresult_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptitudetestresult",
            name="screenshot_violations",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="proctoringviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("phone_detected", "Phone Detected"),
                    ("multiple_persons", "Multiple Persons Detected"),
                    ("no_face_detected", "No Face Detected"),
                    ("tab_switch", "Tab Switch"),
                    ("screenshot_attempt", "Screenshot Attempt"),
                ],
                max_length=50,
            ),
        ),
    ]
