# Generated by Django 5.2.12 on 2026-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0010_aptitudetestresult_screenshot_violations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proctoringviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("phone_detected", "Phone Detected"),
                    ("multiple_persons", "Multiple Persons Detected"),
                    ("no_face_detected", "No Face Detected"),
                    ("tab_switch", "Tab Switch"),
                ],
                max_length=50,
            ),
        ),
    ]
