# Generated by Django 5.2.12 on 2026-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0011_alter_proctoringviolation_violation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptitudetestresult",
            name="audio_violations_triggered",
            field=models.BooleanField(default=False),
        ),
    ]
