# Generated by Django 5.2.12 on 2026-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0012_aptitudetestresult_audio_violations_triggered"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptitudetestresult",
            name="proctoring_summary",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="proctoringviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("phone_detected", "Phone Detected"),
                    ("multiple_persons", "Multiple Persons Detected"),
                    ("no_face_detected", "No Face Detected"),
                    ("tab_switch", "Tab Switch"),
                    ("camera_off", "Camera Turned Off"),
                    ("mic_off", "Microphone Turned Off"),
                    ("device_detected", "Unknown Device Detected"),
                    ("audio_violation", "Loud Noise / Multiple Voices"),
                ],
                max_length=50,
            ),
        ),
    ]
