# Generated by Django 5.2.12 on 2026-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0013_aptitudetestresult_proctoring_summary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aptitudetestresult",
            old_name="proctoring_summary",
            new_name="proctoring_logs",
        ),
        migrations.RemoveField(
            model_name="aptitudetestresult",
            name="audio_violations_triggered",
        ),
        migrations.AlterField(
            model_name="proctoringviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("phone_detected", "Phone Detected"),
                    ("multiple_persons", "Multiple Persons Detected"),
                    ("no_face_detected", "No Face Detected"),
                    ("tab_switch", "Tab Switch"),
                ],
                max_length=50,
            ),
        ),
    ]
