# Generated by Django 5.2.12 on 2026-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_certifications_user_designation_user_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("HR", "HR"),
                    ("PROFESSIONAL", "Professional"),
                    ("ALUMNI", "Alumni"),
                    ("ADMIN", "Admin"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
