# Generated by Django 5.2.12 on 2026-04-15 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=True,
                help_text="Set to False for PLACEMENT_ADMIN until manually verified by staff",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("HR", "HR"),
                    ("PROFESSIONAL", "Professional"),
                    ("ALUMNI", "Alumni"),
                    ("ADMIN", "Admin"),
                    ("PLACEMENT_ADMIN", "Placement Admin"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlacementProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.CharField(max_length=255)),
                (
                    "college_email",
                    models.EmailField(
                        help_text="Must be an institutional email (.edu / .ac.in)",
                        max_length=254,
                    ),
                ),
                (
                    "college_location",
                    models.CharField(
                        blank=True, help_text="City, State", max_length=255, null=True
                    ),
                ),
                (
                    "university_affiliation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("officer_full_name", models.CharField(max_length=255)),
                (
                    "officer_designation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Training & Placement Officer",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("officer_contact", models.CharField(max_length=20)),
                (
                    "proof_document",
                    models.FileField(
                        help_text="ID Card / Appointment Letter / Authorization Letter",
                        upload_to="placement_proofs/",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
