# Generated by Django 5.2.12 on 2026-05-08 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_verified_alter_user_role_placementprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="college_name",
            field=models.CharField(
                blank=True,
                help_text="Relevant for Student role",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=True,
                help_text="Set to False for HR/PLACEMENT_ADMIN until manually verified by staff",
            ),
        ),
        migrations.CreateModel(
            name="HRProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True,
                        help_text="Company website or LinkedIn URL",
                        null=True,
                    ),
                ),
                (
                    "company_location",
                    models.CharField(
                        blank=True,
                        help_text="City, State, Country",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("recruiter_full_name", models.CharField(max_length=255)),
                ("recruiter_designation", models.CharField(max_length=255)),
                ("recruiter_contact", models.CharField(max_length=20)),
                (
                    "roles_hiring_for",
                    models.JSONField(
                        blank=True, default=list, help_text="List of roles being hired"
                    ),
                ),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("eligible_branches", models.JSONField(blank=True, default=list)),
                (
                    "minimum_cgpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Minimum CGPA requirement (e.g. 6.5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "hiring_type",
                    models.CharField(
                        choices=[
                            ("INTERNSHIP", "Internship"),
                            ("FULLTIME", "Full-time"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                (
                    "proof_document",
                    models.FileField(
                        help_text="Company ID / Authorization Letter / Offer Letter",
                        upload_to="hr_proofs/",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
