# Generated by Django 5.2.12 on 2026-05-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_college_name_alter_user_is_verified_hrprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placementprofile",
            name="college_email",
            field=models.EmailField(
                blank=True,
                help_text="Must be an institutional email (.edu / .ac.in)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="placementprofile",
            name="officer_full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
