# Generated by Django 6.0.3 on 2026-03-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViolationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("TAB_SWITCH", "Tab Switch/Blur"),
                            ("COPY_PASTE", "Copy / Paste detected"),
                            ("NO_FACE", "No Face Detected (if applicable)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="interviews.interview",
                    ),
                ),
            ],
        ),
    ]
