# Generated by Django 5.2.12 on 2026-03-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_interviewschedule_interviewattempt"),
        ("proctoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationlog",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="violations",
                to="interviews.interviewschedule",
            ),
        ),
    ]
