# Generated by Django 5.2.12 on 2026-03-13 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0002_alter_violationlog_interview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProctoringViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_id",
                    models.IntegerField(
                        help_text="ID of the AptitudeTestResult (or 0 if test not yet submitted)"
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("phone_detected", "Phone Detected"),
                            ("multiple_persons", "Multiple Persons Detected"),
                            ("no_face_detected", "No Face Detected"),
                            ("tab_switch", "Tab Switch"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
