# Generated by Django 5.2.12 on 2026-03-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True, help_text="e.g., 2-4 years", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="technology_stack",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REVIEWED", "Under Review"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("INTERVIEWING", "Interviewing"),
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
